[scanner]
source_port = 43169

[scanner.xdp]
umem = { chunk_count = 4096, chunk_size = 2048 }
ring = { fill = 4096, completion = 4096, rx = 4096, tx = 4096 }
socket = { busy_poll_budget = 64, queue_ids = [0, 1, 2, 3] }
